### ISSUE TITLE
Update node-persist dependency to remove deprecated q package

### ISSUE THREAD

**Issue by tim-fin** [homebridge/HAP-NodeJS#1107]
## Summary

`hap-nodejs` depends on `node-persist@0.0.12`, which in turn depends on the deprecated `q@1.1.2` promise library. This causes deprecation warnings during installation.

## Current Dependency Chain

```
hap-nodejs@1.2.0
└── node-persist@0.0.12
    └── q@1.1.2 (deprecated)
```

## Deprecation Message

```
You or someone you depend on is using Q, the JavaScript Promise 
library that gave JavaScript developers strong feelings about promises. 
They can almost certainly migrate to the native JavaScript promise now.
```

## Suggested Fix

Update to `node-persist@4.x` which:
- Uses native Promises instead of Q
- Has been actively maintained
- Dropped the `q` dependency entirely

Note: `node-persist` 4.x has API changes from 0.x, so this would require updating the storage code in hap-nodejs accordingly.

## Environment

- hap-nodejs version: 1.2.0 (latest)
- node-persist version: 0.0.12 (pinned)
- Node.js: 22.x

## References

- [node-persist releases](https://github.com/simonlast/node-persist/releases)
- [Q deprecation notice](https://www.npmjs.com/package/q)

**Comment by n0rt0nthec4t** [comment]
Ive raised this before under #1091 It was closed without any action on part of the devs

**Comment by tim-fin** [comment]
Looks like #1109 was opened to address this — it upgrades node-persist to 4.x with a migration strategy for the file format change that @bwp91 flagged in #1091. Could use some maintainer eyes on the review comments there.

**Comment by bwp91** [comment]
You are right that this is still real — I checked a clean install of v2.1.9 and `q` is indeed still pulled in through `node-persist@0.0.12`.

I am going to close this one, and I would rather explain why than leave it sitting open indefinitely. Moving to node-persist 4.x is not really a version bump. The on-disk format changes, and it is not only our own files at stake — third-party projects read those persisted files directly, so a migration that gets it wrong loses people's accessory data with no easy way back. Doing it properly is a sizeable piece of work, and it belongs alongside the other breaking changes in v3.0.0 rather than in a patch release.

In the meantime the deprecation notice is noisy rather than harmful. `q` still works, it is just no longer maintained.

#1109 has an attempt at the migration and stays open, so the work is tracked there rather than here. Thanks for the clear write-up and for laying out the dependency chain.

**Comment by tim-fin** [comment]
Thanks for writing that out rather than just closing it.

One detail that may make the format concern stronger than stated: 0.0.12 writes each key to `<dir>/<key>` containing the bare JSON value. 3.0.0 switched filenames to `md5(key)` and wrapped contents as `{key, value, ttl}`; 4.x moved the hash to sha256. So a third party looking for a file named after the accessory breaks on the filename alone, which no migration inside HAP-NodeJS can help with.

Small correction to my original report, too: `q` actually drops out at node-persist 3.0.0, not 4.x. That doesn't really change the conclusion, since 3.0.0 is also where the filename hashing starts.

One option that might sidestep the tradeoff: HAP-NodeJS only uses four operations — `initSync`, `getItem`, `setItemSync`, `removeItemSync` — across `AccessoryInfo`, `IdentifierCache` and `ControllerStorage`. That's on the order of 50 lines of `fs` against the existing layout. It would drop `q` while keeping the on-disk format and the synchronous call sites exactly as they are, with no migration, so it wouldn't need to wait for v3.0.0.

The obvious hole is that `HAPStorage.storage()` is public, so plugins may be using more of node-persist than you do internally — you'd know that far better than I would.

Happy to put a PR together if that'd be useful, or to leave it here.

**Comment by bwp91** [comment]
Thank you — both of your corrections are right, and the suggestion is better than what I closed this for.

I checked the API surface rather than taking it on trust, and it is exactly the four you name. Every call on `HAPStorage.storage()` across the whole source tree:

- `initSync` (in `HAPStorage` itself)
- `getItem` ×3
- `setItemSync` ×3
- `removeItemSync` ×4

Nothing else. No `keys`, no iteration, no TTL.

**There is a second problem with upgrading that I had not spotted, and it makes your case stronger.** The call sites treat `getItem` as synchronous:

```ts
const saved = HAPStorage.storage().getItem(key);

if (saved) {
```

That works on `0.0.12`, where `getItem` returns the value. From `3.0.0` it returns a Promise — and a Promise is always truthy, so that check silently stops meaning anything. Which means the upgrade is not only a file-format migration: every storage call site has to become `async`, and that propagates out through `AccessoryInfo.load()`, `IdentifierCache.load()` and `ControllerStorage` into their public signatures. #1109 does exactly that, and it is the main reason I see that PR as v3.0.0 material rather than a patch.

Your shim sidesteps all of it. Same on-disk layout, same synchronous semantics, no migration, no signature changes — and `q` still goes. That is a much better trade than the one I was weighing when I closed this, so I have reopened it.

The hole you identified is the real one, and you are right to flag it. `HAPStorage` is exported from the package index, so `HAPStorage.storage()` is public API returning node-persist's `LocalStorage`. A plugin could legitimately be calling something outside those four methods, and I have no way to measure how many do.

My instinct is that it is still worth doing, because narrowing that surface is a far smaller risk than either losing people's accessory data or turning the storage API async. But I would want the shim to fail loudly rather than quietly on anything it does not implement, so that a plugin depending on more gets a clear error instead of undefined behaviour.

**So yes please, a PR would be very welcome.** Suggested scope:

- Back `AccessoryInfo`, `IdentifierCache` and `ControllerStorage` with the new `fs` implementation
- Keep the existing on-disk layout byte-for-byte — no filename hashing, no wrapper object
- Keep the four methods synchronous, so no call site changes shape
- Have anything outside those four throw with a message saying what happened and why

Worth keeping #1109 open alongside it for now, since it is a different bet and the comparison is useful.

**Comment by ebaauw** [comment]
Just chiming in: the alternative approach using `fs` looks good to me.  I don’t use `HAPStorage` in any of my plugins, and wasn’t even aware of it being exposed.  The original 3.0 approach also seems valid to me.  I think most homebridge plugins, like mine, wouldn’t concern themselves with `AccessoryInfo` nor `IdentifierCache`.  I haven’t come across `ControllerStorage`.

My plugins do depend on `cachedAccessories` as maintained by Homebridge for dynamic platform plugins.  I use the `context` on the `PlatformAccessory` to persist plugin-specific info (like the Eve history).
